#!/usr/bin/env python3
"""R15 no-ai-attribution: commit message KHÔNG được ghi công cho AI.

Contract (xem harness/recipe.md):
  - commit-msg mode : no_ai_attribution.py --commit-msg <COMMIT_MSG_FILE>
                      (pre-commit stage `commit-msg` tự nối path file message vào cuối)
  - selftest        : no_ai_attribution.py --selftest
  - exit 0 = pass, exit 2 = vi phạm (lý do ra stderr)

Fail-open: thiếu file / đọc hỏng → exit 0 (lỗi hạ tầng không khoá người dùng — ADR-002).
Chỉ quét COMMIT MESSAGE (không quét nội dung file — quyết định phạm vi, ADR-016).
"""
import re
import sys

# Trailer ghi công đồng-tác-giả là AI (Co-Authored-By: <ai>).
COAUTHOR_AI = re.compile(
    r"co-?authored-by:.*\b(claude|anthropic|gpt|chatgpt|copilot|cursor|gemini|bard|llm|codex)\b",
    re.IGNORECASE,
)
# "Generated with <ai>" / "Generated by <ai>".
GENERATED_AI = re.compile(
    r"generated (?:with|by).*\b(claude|anthropic|gpt|chatgpt|copilot|cursor|gemini|codex|ai)\b",
    re.IGNORECASE,
)
# Robot emoji — dấu hiệu credit AI mà template hay chèn.
ROBOT_EMOJI = re.compile("\U0001F916")


def scan(message: str):
    """Trả về lý do vi phạm đầu tiên (str) hoặc None nếu sạch."""
    for line in message.splitlines():
        if COAUTHOR_AI.search(line):
            return f"trailer ghi cong dong-tac-gia AI: {line.strip()[:120]}"
        if GENERATED_AI.search(line):
            return f"dong 'Generated with/by AI': {line.strip()[:120]}"
        if ROBOT_EMOJI.search(line):
            return f"emoji robot (credit AI): {line.strip()[:120]}"
    return None


def fail(reason: str) -> None:
    print(
        f"[R15 no-ai-attribution] {reason}\n"
        "  -> Commit message KHONG duoc ghi cong cho AI. Xoa dong Co-Authored-By/Generated-with/robot.",
        file=sys.stderr,
    )
    sys.exit(2)


def selftest() -> None:
    dirty = [
        "feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
        "fix\n\n\U0001F916 Generated with Claude Code",
        "chore\n\nco-authored-by: gpt-4 <x@y>",
        "Generated by Copilot",
    ]
    clean = [
        "feat: x\n\nCo-Authored-By: Alice <alice@example.com>",
        "fix: robot arm kinematics for the AI-generated dataset loader",  # 'AI' trong prose, không phải trailer
        "chore: bump deps",
    ]
    ok = True
    for m in dirty:
        if scan(m) is None:
            ok = False
            print(f"  SELFTEST FAIL (nen bat): {m!r}", file=sys.stderr)
    for m in clean:
        if scan(m) is not None:
            ok = False
            print(f"  SELFTEST FAIL (nen sach): {m!r} -> {scan(m)}", file=sys.stderr)
    print("R15 selftest:", "PASS" if ok else "FAIL")
    sys.exit(0 if ok else 1)


def main() -> None:
    args = sys.argv[1:]
    if "--selftest" in args:
        selftest()
    if "--commit-msg" in args:
        paths = [a for a in args if a != "--commit-msg"]
        for p in paths:
            try:
                with open(p, encoding="utf-8", errors="replace") as f:
                    msg = f.read()
            except Exception:
                sys.exit(0)  # fail-open
            reason = scan(msg)
            if reason:
                fail(reason)
    sys.exit(0)


if __name__ == "__main__":
    main()
